apiVersion: apps/v1
kind: Deployment
metadata:
  name: tts-app
spec:
  selector:
    matchLabels:
      app: tts-app
  replicas: 2
  template:
    metadata:
      labels:
        app: tts-app
    spec:
      containers:
      - name: tts-app
        image: peeweeto/tts-app:1.0
        ports:
        - containerPort: 8080
