apiVersion: v1
kind: Service
metadata:
  name: local-tts-spring-boot-service
spec:
  selector:
    app: local-tts-spring-boot
  ports:
  - port: 8089
    protocol: TCP
    targetPort: 8080
  #  nodePort: 31111
  type: NodePort